[theme]
base = "light"
primaryColor = "#245846"
backgroundColor = "#f8f6f0"
secondaryBackgroundColor = "#eaece3"
textColor = "#183c37"
font = "sans serif"
[server]
headless = true
[browser]
gatherUsageStats = false
