[theme]
base = "light"
primaryColor = "#087f75"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#eaf0f5"
textColor = "#17243a"
font = "sans serif"
[server]
headless = true
[browser]
gatherUsageStats = false
